[package]
name = "fivewsdb"
version = "0.1.0"
authors = ["Ingi Thor Sigurdsson <ingisigurds@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
structopt = "0.3.21"
thiserror = "1.0"